name = "SimOptDecisions"
uuid = "8764eb7a-9599-4112-a7c7-9b4115e89f97"
version = "0.1.0"
authors = ["James Doss-Gollin <jdossgollin@rice.edu>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extensions]
SimOptCSVExt = "CSV"
SimOptMakieExt = "Makie"
SimOptMetaheuristicsExt = "Metaheuristics"
SimOptNetCDFExt = "NCDatasets"

[compat]
Aqua = "0.8"
CSV = "0.10"
CairoMakie = "0.12 - 0.15"
Dates = "1"
GLMakie = "0.10 - 0.11"
JLD2 = "0.5, 0.6"
Makie = "0.20 - 0.24"
Metaheuristics = "3"
NCDatasets = "0.12, 0.13, 0.14, 0.15"
OrderedCollections = "1.8.1"
ProgressMeter = "1"
Random = "1"
Statistics = "1"
TOML = "1"
Tables = "1"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "CairoMakie", "Metaheuristics", "NCDatasets", "Test"]
