name = "SimOptDecisions"
uuid = "8764eb7a-9599-4112-a7c7-9b4115e89f97"
version = "0.1.0"
authors = ["James Doss-Gollin <jdossgollin@rice.edu>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"

[extensions]
SimOptMetaheuristicsExt = "Metaheuristics"
SimOptMakieExt = ["CairoMakie", "GLMakie"]

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]

[compat]
Aqua = "0.8"
CairoMakie = "0.12, 0.13"
GLMakie = "0.10, 0.11"
JLD2 = "0.5, 0.6"
Metaheuristics = "3"
Tables = "1"
julia = "1.10"
